ecommerce_inmakes/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('cart-items/', views.cartdetail, name="cart_detail"),
    path('add/<uuid:prod_id>/', views.add_cart, name="add_cart"),
    path('remove/<uuid:prod_id>/', views.cartitemremove, name="cart_item_remove"),
    path('clear/<uuid:prod_id>/', views.cartclear, name="cart_clear"),
]

ecommerce_inmakes/ecommerce_inmakes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('search-app/search/', include('searchapp.urls', namespace='searchapp')),
    path('cart-app/cart/', include('cart.urls', namespace='cart')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_inmakes/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.allProdCat, name="allprodcat"),
    path('<slug:cat_slug>/', views.allProdCat, name="products_by_category"),
    path('<slug:cat_slug>/<slug:prod_slug>/', views.productDetail,
         name="product_category_detail"),
]

ecommerce_inmakes/cart/models.py
from django.db import models
from shop.models import ProductModel, CategoryModel
from django.utils.translation import gettext_lazy as _


class Cart(models.Model):
    cart_id = models.CharField(max_length=128, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart_cart'
        ordering = ['-date_added']
        verbose_name = _('cart')
        verbose_name_plural = _('carts')

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'cart_cart_item'
        verbose_name = _('cart_item')
        verbose_name_plural = _('cart_items')

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_inmakes/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import ProductModel
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# CREATE CART ID WITH SESSION ID
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, prod_id):
    product = ProductModel.objects.get(pk=prod_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cartdetail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart/cart.html',
                  dict(cartitems=cart_items, total=total, counter=counter))


def cartitemremove(request, prod_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(ProductModel, id=prod_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def cartclear(request, prod_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(ProductModel, id=prod_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce_inmakes/templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}

{% block meta_description %}
    Cart Details
{% endblock %}

{% block title %}
    Cart - ABC Store
{% endblock %}

{% block content %}
    {% if not cartitems %}
        <div>
            <div class="text-center">
                <br />
                <h1 class="text-center my-title">Your cart is empty</h1>
                <br />
                <p class="text-center">Please click
                    <a href="{% url 'shop:allprodcat' %}">here</a> to continue</p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br />
                <h1 class="text-center my-title">Your cart</h1>
                <br />
            </div>
        </div>

        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my-table">
                    <thead class="my-thead">
                        <tr>
                            <th colspan="5">
                                Your Items
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for cartitem in cartitems %}
                        <tr>
                            <td>
                                <a href="cartitem.product.get_absolute_url">
                                    <img src="{{cartitem.product.image.url}}"
                                         alt="{{cartitem.product.name}}"
                                         class="float-left rounded custom-image" />
                                </a>
                            </td>
                            <td class="text-left">
                                {{cartitem.product.name}}
                                <br />
                                SKU: {{cartitem.product.id}}
                                <br />
                                Price: ${{cartitem.product.price}}
                                <br />
                                Qty: {{cartitem.quantity}} x $ {{cartitem}}
                            </td>
                            <td>
                                $ {{cartitem.sub_total}}
                            </td>
                            {% if cartitem.quantity < cartitem.product.stock %}
                                <td>
                                    <a href="{% url 'cart:add_cart' cartitem.product.id %}"
                                        class="custom-a">
                                        <i class="fa fa-plus custom-icon"></i>
                                    </a>&nbsp;
                                    <a
                                        href="{% url 'cart:cart_item_remove' cartitem.product.id %}"
                                        class="custom-a">
                                        <i class="fa fa-minus custom-icon"></i>
                                    </a>
                                    <a href="{% url 'cart:cart_clear' cartitem.product.id %}"
                                        class="custom-a">
                                        <i class="fa fa-trash custom-icon"></i>
                                    </a>
                                </td>
                            {% else %}
                                <td>
                                    <a href="{% url 'cart:cart_item_remove' cartitem.product.id %}"
                                        class="custom-a">
                                        <i class="fa fa-minus custom-icon"></i>
                                    </a>
                                    <a href="{% url 'cart:cart_clear' cartitem.product.id %}"
                                        class="custom-a">
                                        <i class="fa fa-trash custom-icon"></i>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my-table">
                    <thead class="my-thead">
                        <tr>
                            <th>Checkout</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your items before proceeding with the payment.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your total is <strong>$ {{total}}</strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mx-auto">
                    <a href="{% url 'shop:allprodcat' %}" class="btn btn-secondary btn-block my-button">
                        Continue Shopping
                    </a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}