ecommerce_inmakes/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('cart-items/', views.cartdetail, name="cart_detail"),
    path('add/<uuid:prod_id>/', views.add_cart, name="add_cart"),
    path('remove/<uuid:prod_id>/', views.cartitemremove, name="cart_item_remove"),
    path('clear/<uuid:prod_id>/', views.cartclear, name="cart_clear"),
]

ecommerce_inmakes/ecommerce_inmakes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('search-app/search/', include('searchapp.urls', namespace='searchapp')),
    path('cart-app/cart/', include('cart.urls', namespace='cart')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_inmakes/searchapp/urls.py
from django.urls import path
from . import views


app_name = 'searchapp'
urlpatterns = [
    path('search/', views.searchResult, name="search_result"),
]

ecommerce_inmakes/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.allProdCat, name="allprodcat"),
    path('<slug:cat_slug>/', views.allProdCat, name="products_by_category"),
    path('<slug:cat_slug>/<slug:prod_slug>/', views.productDetail,
         name="product_category_detail"),
]

ecommerce_inmakes/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block meta_description %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap"
          rel="stylesheet">

    <script src="{% static 'js/fontawesome.js' %}"></script>
</head>
<body>
    <div class="container">
        {% include 'base/header.html' %}
        {% include 'base/navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'base/footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerce_inmakes/templates/base/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">&copy; copyright ABC pvt. ltd. All rights reserved</p>
</div>

ecommerce_inmakes/templates/base/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allprodcat' %}">
            <img src="{% static 'header/logo.png' %}" alt="logo" />
        </a>
    </center>
</header>

ecommerce_inmakes/templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:allprodcat' %}">
            <img src="{% static 'header/logo.png' %}" alt="logo"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:allprodcat' %}">Home</a>
                </li>
                <li class="nav-item dropdown
                {% if 'shop' in request.path %} active {% endif %}">
                    <a class="nav-link dropdown-toggle"
                       href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Shop
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"
                               href="{% url 'shop:allprodcat' %}">All Products</a>
                        </li>
                        {% for cat in links %}
                            <li><a class="dropdown-item"
                                   href="{{cat.get_url}}">{{cat.name}}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link position-relative" href="{% url 'cart:cart_detail' %}">
                        <i class="fa fa-shopping-cart"></i>
                        <span class="position-absolute top-0 start-100
                            translate-middle badge rounded-circle text-danger my-item-count">
                            {{item_count}}
                        </span>
                    </a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search"
                  action="{% url 'searchapp:search_result' %}" method="get">
                {% csrf_token %}
                <input class="form-control me-2" type="search" name="q" placeholder="Search"
                       aria-label="Search">
                <button class="btn btn-outline-success" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </form>
        </div>
    </div>
</nav>